BASE="https://rmkmqafgjbpisopuaxle.supabase.co/storage/v1/object/public/assets"

sed -i '' "s|src=\"/11.png\"|src=\"$BASE/11.png\"|g" "app/(dashboard)/maps/page.tsx"
sed -i '' "s|src=\"/tugas.png\"|src=\"$BASE/tugas.png\"|g" "app/(dashboard)/tugas/page.tsx"
sed -i '' "s|src: '/35.png'|src: '$BASE/35.png'|g" "app/(dashboard)/harian/page.tsx"
sed -i '' "s|src: '/36.png'|src: '$BASE/36.png'|g" "app/(dashboard)/harian/page.tsx"
sed -i '' "s|src: '/37.png'|src: '$BASE/37.png'|g" "app/(dashboard)/harian/page.tsx"
sed -i '' "s|src: '/38.png'|src: '$BASE/38.png'|g" "app/(dashboard)/harian/page.tsx"
sed -i '' "s|src: '/39.png'|src: '$BASE/39.png'|g" "app/(dashboard)/harian/page.tsx"
sed -i '' "s|src: '/40.png'|src: '$BASE/40.png'|g" "app/(dashboard)/harian/page.tsx"
sed -i '' "s|src: '/41.png'|src: '$BASE/41.png'|g" "app/(dashboard)/harian/page.tsx"
sed -i '' "s|src: '/42.png'|src: '$BASE/42.png'|g" "app/(dashboard)/harian/page.tsx"
sed -i '' "s|new Audio(\"/lagu.mp3\")|new Audio(\"$BASE/lagu.mp3\")|g" "app/(dashboard)/dashboard/page.tsx"
sed -i '' "s|src=\"/cinta.png\"|src=\"$BASE/cinta.png\"|g" "app/(dashboard)/dashboard/page.tsx"
sed -i '' "s|src=\"/petualang.png\"|src=\"$BASE/petualang.png\"|g" "app/(dashboard)/edukasi/page.tsx"
sed -i '' "s|useState('/profile.png')|useState('$BASE/profile.png')|g" "app/(dashboard)/profile/page.tsx"
sed -i '' "s|new Audio(\`/\${key}.mp3\`)|new Audio(\`$BASE/\${key}.mp3\`)|g" "app/(dashboard)/profile/page.tsx"
sed -i '' "s|d.profileImage ?? '/profile.png'|d.profileImage ?? '$BASE/profile.png'|g" "app/(dashboard)/profile/page.tsx"
sed -i '' "s|profileImage: '/profile.png'|profileImage: '$BASE/profile.png'|g" "app/(dashboard)/profile/page.tsx"
sed -i '' "s|src: '/35.png'|src: '$BASE/35.png'|g" "app/(dashboard)/pet-academy/page.tsx"
sed -i '' "s|src: '/36.png'|src: '$BASE/36.png'|g" "app/(dashboard)/pet-academy/page.tsx"
sed -i '' "s|src: '/37.png'|src: '$BASE/37.png'|g" "app/(dashboard)/pet-academy/page.tsx"
sed -i '' "s|src: '/38.png'|src: '$BASE/38.png'|g" "app/(dashboard)/pet-academy/page.tsx"
sed -i '' "s|src: '/39.png'|src: '$BASE/39.png'|g" "app/(dashboard)/pet-academy/page.tsx"
sed -i '' "s|src: '/40.png'|src: '$BASE/40.png'|g" "app/(dashboard)/pet-academy/page.tsx"
sed -i '' "s|src: '/41.png'|src: '$BASE/41.png'|g" "app/(dashboard)/pet-academy/page.tsx"
sed -i '' "s|src: '/42.png'|src: '$BASE/42.png'|g" "app/(dashboard)/pet-academy/page.tsx"
sed -i '' "s|src=\"/maskot3/maskot3.png\"|src=\"$BASE/maskot3/maskot3.png\"|g" "app/login/page.tsx"
sed -i '' "s|src=\"/23.png\"|src=\"$BASE/23.png\"|g" "components/Footer.tsx"
sed -i '' "s|src=\"/23.png\"|src=\"$BASE/23.png\"|g" "components/Sidebar.tsx"
sed -i '' "s|src=\"/maskotwebsite.png\"|src=\"$BASE/maskotwebsite.png\"|g" "components/Sidebar.tsx"
sed -i '' "s|'/14.png'|'$BASE/14.png'|g" "components/MascotPopup.tsx"
sed -i '' "s|'/16.png'|'$BASE/16.png'|g" "components/MascotPopup.tsx"
sed -i '' "s|src: '/15.png'|src: '$BASE/15.png'|g" "components/PlottwistPro.tsx"
sed -i '' "s|src: '/18.png'|src: '$BASE/18.png'|g" "components/PlottwistPro.tsx"
sed -i '' "s|src: '/17.png'|src: '$BASE/17.png'|g" "components/PlottwistPro.tsx"
sed -i '' "s|src: '/16.png'|src: '$BASE/16.png'|g" "components/PlottwistPro.tsx"
sed -i '' "s|src: '/14.png'|src: '$BASE/14.png'|g" "components/PlottwistPro.tsx"
sed -i '' "s|src: '/35.png'|src: '$BASE/35.png'|g" "hooks/useActivePet.ts"
sed -i '' "s|src: '/36.png'|src: '$BASE/36.png'|g" "hooks/useActivePet.ts"
sed -i '' "s|src: '/37.png'|src: '$BASE/37.png'|g" "hooks/useActivePet.ts"
sed -i '' "s|src: '/38.png'|src: '$BASE/38.png'|g" "hooks/useActivePet.ts"
sed -i '' "s|src: '/39.png'|src: '$BASE/39.png'|g" "hooks/useActivePet.ts"
sed -i '' "s|src: '/40.png'|src: '$BASE/40.png'|g" "hooks/useActivePet.ts"
sed -i '' "s|src: '/41.png'|src: '$BASE/41.png'|g" "hooks/useActivePet.ts"
sed -i '' "s|src: '/42.png'|src: '$BASE/42.png'|g" "hooks/useActivePet.ts"

echo "Selesai!"
